// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/presentation/ui/features/about/components/changelog_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/widgets.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:whph/presentation/ui/shared/services/abstraction/i_translation_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [ITranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITranslationService extends _i1.Mock
    implements _i3.ITranslationService {
  MockITranslationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String translate(String? key, {Map<String, String>? namedArgs}) =>
      (super.noSuchMethod(
            Invocation.method(#translate, [key], {#namedArgs: namedArgs}),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#translate, [key], {#namedArgs: namedArgs}),
            ),
          )
          as String);

  @override
  _i4.Future<void> changeLanguage(
    _i2.BuildContext? context,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [context, languageCode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> changeLanguageWithoutNavigation(
    _i2.BuildContext? context,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguageWithoutNavigation, [
              context,
              languageCode,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String getCurrentLanguage(_i2.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLanguage, [context]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getCurrentLanguage, [context]),
            ),
          )
          as String);

  @override
  _i2.Widget wrapWithTranslations(_i2.Widget? child) =>
      (super.noSuchMethod(
            Invocation.method(#wrapWithTranslations, [child]),
            returnValue: _FakeWidget_0(
              this,
              Invocation.method(#wrapWithTranslations, [child]),
            ),
          )
          as _i2.Widget);
}
