// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/core/application/features/tasks/queries/get_list_tasks_query_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:acore/acore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:whph/core/application/features/sync/models/paginated_sync_data.dart'
    as _i3;
import 'package:whph/core/application/features/tasks/models/task_list_item.dart'
    as _i8;
import 'package:whph/core/application/features/tasks/models/task_query_filter.dart'
    as _i7;
import 'package:whph/core/application/features/tasks/services/abstraction/i_task_repository.dart'
    as _i4;
import 'package:whph/core/domain/features/tasks/models/task_with_total_duration.dart'
    as _i6;
import 'package:whph/core/domain/features/tasks/task.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedList_0<T> extends _i1.SmartFake
    implements _i2.PaginatedList<T> {
  _FakePaginatedList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedSyncData_1<T extends _i2.BaseEntity<dynamic>>
    extends _i1.SmartFake
    implements _i3.PaginatedSyncData<T> {
  _FakePaginatedSyncData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ITaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRepository extends _i1.Mock implements _i4.ITaskRepository {
  MockITaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PaginatedList<_i6.TaskWithTotalDuration>>
  getListWithTotalDuration(
    int? pageIndex,
    int? pageSize, {
    bool? includeDeleted = false,
    _i2.CustomWhereFilter? customWhereFilter,
    List<_i2.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getListWithTotalDuration,
              [pageIndex, pageSize],
              {
                #includeDeleted: includeDeleted,
                #customWhereFilter: customWhereFilter,
                #customOrder: customOrder,
              },
            ),
            returnValue:
                _i5.Future<_i2.PaginatedList<_i6.TaskWithTotalDuration>>.value(
                  _FakePaginatedList_0<_i6.TaskWithTotalDuration>(
                    this,
                    Invocation.method(
                      #getListWithTotalDuration,
                      [pageIndex, pageSize],
                      {
                        #includeDeleted: includeDeleted,
                        #customWhereFilter: customWhereFilter,
                        #customOrder: customOrder,
                      },
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.PaginatedList<_i6.TaskWithTotalDuration>>);

  @override
  _i5.Future<_i2.PaginatedList<_i6.TaskWithTotalDuration>> getListWithOptions({
    required int? pageIndex,
    required int? pageSize,
    _i7.TaskQueryFilter? filter,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getListWithOptions, [], {
              #pageIndex: pageIndex,
              #pageSize: pageSize,
              #filter: filter,
              #includeDeleted: includeDeleted,
            }),
            returnValue:
                _i5.Future<_i2.PaginatedList<_i6.TaskWithTotalDuration>>.value(
                  _FakePaginatedList_0<_i6.TaskWithTotalDuration>(
                    this,
                    Invocation.method(#getListWithOptions, [], {
                      #pageIndex: pageIndex,
                      #pageSize: pageSize,
                      #filter: filter,
                      #includeDeleted: includeDeleted,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.PaginatedList<_i6.TaskWithTotalDuration>>);

  @override
  _i5.Future<_i2.PaginatedList<_i6.TaskWithTotalDuration>> getListWithFilter({
    required int? pageIndex,
    required int? pageSize,
    _i7.TaskQueryFilter? filter,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getListWithFilter, [], {
              #pageIndex: pageIndex,
              #pageSize: pageSize,
              #filter: filter,
              #includeDeleted: includeDeleted,
            }),
            returnValue:
                _i5.Future<_i2.PaginatedList<_i6.TaskWithTotalDuration>>.value(
                  _FakePaginatedList_0<_i6.TaskWithTotalDuration>(
                    this,
                    Invocation.method(#getListWithFilter, [], {
                      #pageIndex: pageIndex,
                      #pageSize: pageSize,
                      #filter: filter,
                      #includeDeleted: includeDeleted,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.PaginatedList<_i6.TaskWithTotalDuration>>);

  @override
  _i5.Future<_i2.PaginatedList<_i8.TaskListItem>> getListWithDetails({
    required int? pageIndex,
    required int? pageSize,
    _i7.TaskQueryFilter? filter,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getListWithDetails, [], {
              #pageIndex: pageIndex,
              #pageSize: pageSize,
              #filter: filter,
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i5.Future<_i2.PaginatedList<_i8.TaskListItem>>.value(
              _FakePaginatedList_0<_i8.TaskListItem>(
                this,
                Invocation.method(#getListWithDetails, [], {
                  #pageIndex: pageIndex,
                  #pageSize: pageSize,
                  #filter: filter,
                  #includeDeleted: includeDeleted,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.PaginatedList<_i8.TaskListItem>>);

  @override
  _i5.Future<List<_i9.Task>> getByParentTaskId(String? parentTaskId) =>
      (super.noSuchMethod(
            Invocation.method(#getByParentTaskId, [parentTaskId]),
            returnValue: _i5.Future<List<_i9.Task>>.value(<_i9.Task>[]),
          )
          as _i5.Future<List<_i9.Task>>);

  @override
  _i5.Future<List<_i9.Task>> getByRecurrenceParentId(
    String? recurrenceParentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByRecurrenceParentId, [recurrenceParentId]),
            returnValue: _i5.Future<List<_i9.Task>>.value(<_i9.Task>[]),
          )
          as _i5.Future<List<_i9.Task>>);

  @override
  _i5.Future<_i3.PaginatedSyncData<_i9.Task>> getPaginatedSyncData(
    DateTime? lastSyncDate, {
    int? pageIndex = 0,
    int? pageSize = 200,
    String? entityType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPaginatedSyncData,
              [lastSyncDate],
              {
                #pageIndex: pageIndex,
                #pageSize: pageSize,
                #entityType: entityType,
              },
            ),
            returnValue: _i5.Future<_i3.PaginatedSyncData<_i9.Task>>.value(
              _FakePaginatedSyncData_1<_i9.Task>(
                this,
                Invocation.method(
                  #getPaginatedSyncData,
                  [lastSyncDate],
                  {
                    #pageIndex: pageIndex,
                    #pageSize: pageSize,
                    #entityType: entityType,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.PaginatedSyncData<_i9.Task>>);

  @override
  _i5.Future<void> hardDeleteSoftDeleted(DateTime? beforeDate) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteSoftDeleted, [beforeDate]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> truncate() =>
      (super.noSuchMethod(
            Invocation.method(#truncate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.PaginatedList<_i9.Task>> getList(
    int? pageIndex,
    int? pageSize, {
    bool? includeDeleted = false,
    _i2.CustomWhereFilter? customWhereFilter,
    List<_i2.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getList,
              [pageIndex, pageSize],
              {
                #includeDeleted: includeDeleted,
                #customWhereFilter: customWhereFilter,
                #customOrder: customOrder,
              },
            ),
            returnValue: _i5.Future<_i2.PaginatedList<_i9.Task>>.value(
              _FakePaginatedList_0<_i9.Task>(
                this,
                Invocation.method(
                  #getList,
                  [pageIndex, pageSize],
                  {
                    #includeDeleted: includeDeleted,
                    #customWhereFilter: customWhereFilter,
                    #customOrder: customOrder,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.PaginatedList<_i9.Task>>);

  @override
  _i5.Future<List<_i9.Task>> getAll({
    bool? includeDeleted = false,
    _i2.CustomWhereFilter? customWhereFilter,
    List<_i2.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #includeDeleted: includeDeleted,
              #customWhereFilter: customWhereFilter,
              #customOrder: customOrder,
            }),
            returnValue: _i5.Future<List<_i9.Task>>.value(<_i9.Task>[]),
          )
          as _i5.Future<List<_i9.Task>>);

  @override
  _i5.Future<_i9.Task?> getById(String? id, {bool? includeDeleted = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getById,
              [id],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i5.Future<_i9.Task?>.value(),
          )
          as _i5.Future<_i9.Task?>);

  @override
  _i5.Future<_i9.Task?> getFirst(
    _i2.CustomWhereFilter? customWhereFilter, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFirst,
              [customWhereFilter],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i5.Future<_i9.Task?>.value(),
          )
          as _i5.Future<_i9.Task?>);

  @override
  _i5.Future<void> add(_i9.Task? item) =>
      (super.noSuchMethod(
            Invocation.method(#add, [item]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> update(_i9.Task? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(_i9.Task? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
