// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/infrastructure/linux/features/setup/linux_setup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:infrastructure_linux/features/setup/services/abstraction/i_linux_desktop_service.dart'
    as _i4;
import 'package:infrastructure_linux/features/setup/services/abstraction/i_linux_firewall_service.dart'
    as _i2;
import 'package:infrastructure_linux/features/setup/services/abstraction/i_linux_kde_service.dart'
    as _i5;
import 'package:infrastructure_linux/features/setup/services/abstraction/i_linux_update_service.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ILinuxFirewallService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILinuxFirewallService extends _i1.Mock
    implements _i2.ILinuxFirewallService {
  MockILinuxFirewallService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> checkFirewallRule({
    required String? ruleName,
    String? protocol = 'TCP',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkFirewallRule, [], {
              #ruleName: ruleName,
              #protocol: protocol,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> addFirewallRule({
    required String? ruleName,
    required String? appPath,
    required String? port,
    String? protocol = 'TCP',
    String? direction = 'in',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addFirewallRule, [], {
              #ruleName: ruleName,
              #appPath: appPath,
              #port: port,
              #protocol: protocol,
              #direction: direction,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFirewallRule({required String? ruleName}) =>
      (super.noSuchMethod(
            Invocation.method(#removeFirewallRule, [], {#ruleName: ruleName}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ILinuxDesktopService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILinuxDesktopService extends _i1.Mock
    implements _i4.ILinuxDesktopService {
  MockILinuxDesktopService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> updateDesktopFile(
    String? filePath,
    String? iconPath,
    String? appDir,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDesktopFile, [filePath, iconPath, appDir]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateIconCache(String? sharePath) =>
      (super.noSuchMethod(
            Invocation.method(#updateIconCache, [sharePath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> installSystemIcon(String? sourceIcon) =>
      (super.noSuchMethod(
            Invocation.method(#installSystemIcon, [sourceIcon]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ILinuxKdeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILinuxKdeService extends _i1.Mock implements _i5.ILinuxKdeService {
  MockILinuxKdeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> detectKDEEnvironment() =>
      (super.noSuchMethod(
            Invocation.method(#detectKDEEnvironment, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setupKDEIntegration(String? appDir) =>
      (super.noSuchMethod(
            Invocation.method(#setupKDEIntegration, [appDir]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> installKDEDBusService(String? appDir) =>
      (super.noSuchMethod(
            Invocation.method(#installKDEDBusService, [appDir]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> registerKDEMimeTypes(String? appDir) =>
      (super.noSuchMethod(
            Invocation.method(#registerKDEMimeTypes, [appDir]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> configureKDEWindowProperties() =>
      (super.noSuchMethod(
            Invocation.method(#configureKDEWindowProperties, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ILinuxUpdateService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILinuxUpdateService extends _i1.Mock
    implements _i6.ILinuxUpdateService {
  MockILinuxUpdateService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> downloadAndInstallUpdate(String? downloadUrl) =>
      (super.noSuchMethod(
            Invocation.method(#downloadAndInstallUpdate, [downloadUrl]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getAppVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getAppVersion, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getAppVersion, []),
              ),
            ),
          )
          as _i3.Future<String>);
}
