name: Feature Request
description: Suggest an idea for WHPH
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: Ex. I'm always frustrated when [...]

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: Have you thought of other ways to solve this?

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What area of the app does this feature relate to?
      options:
        - Task Management
        - Habit Tracking
        - Time Tracking
        - App Usage Monitoring
        - Notes
        - Settings
        - UI/UX
        - Performance
        - Sync/Export
        - Other

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
