// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/infrastructure/windows/features/setup/windows_setup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:whph/infrastructure/windows/features/setup/services/abstraction/i_windows_firewall_service.dart'
    as _i2;
import 'package:whph/infrastructure/windows/features/setup/services/abstraction/i_windows_shortcut_service.dart'
    as _i4;
import 'package:whph/infrastructure/windows/features/setup/services/abstraction/i_windows_update_service.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IWindowsFirewallService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWindowsFirewallService extends _i1.Mock
    implements _i2.IWindowsFirewallService {
  MockIWindowsFirewallService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addFirewallRules({
    required String? ruleNamePrefix,
    required String? appPath,
    required String? port,
    String? protocol = 'TCP',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addFirewallRules, [], {
              #ruleNamePrefix: ruleNamePrefix,
              #appPath: appPath,
              #port: port,
              #protocol: protocol,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addFirewallRule({
    required String? ruleName,
    required String? appPath,
    required String? port,
    String? protocol = 'TCP',
    String? direction = 'in',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addFirewallRule, [], {
              #ruleName: ruleName,
              #appPath: appPath,
              #port: port,
              #protocol: protocol,
              #direction: direction,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkFirewallRule({
    required String? ruleName,
    String? protocol = 'TCP',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkFirewallRule, [], {
              #ruleName: ruleName,
              #protocol: protocol,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> removeFirewallRule({required String? ruleName}) =>
      (super.noSuchMethod(
            Invocation.method(#removeFirewallRule, [], {#ruleName: ruleName}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IWindowsShortcutService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWindowsShortcutService extends _i1.Mock
    implements _i4.IWindowsShortcutService {
  MockIWindowsShortcutService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createStartMenuShortcut({
    required String? appName,
    required String? target,
    required String? iconPath,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createStartMenuShortcut, [], {
              #appName: appName,
              #target: target,
              #iconPath: iconPath,
              #description: description,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createShortcut({
    required String? target,
    required String? shortcutPath,
    required String? iconPath,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createShortcut, [], {
              #target: target,
              #shortcutPath: shortcutPath,
              #iconPath: iconPath,
              #description: description,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IWindowsUpdateService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWindowsUpdateService extends _i1.Mock
    implements _i5.IWindowsUpdateService {
  MockIWindowsUpdateService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> downloadAndInstallUpdate(String? downloadUrl) =>
      (super.noSuchMethod(
            Invocation.method(#downloadAndInstallUpdate, [downloadUrl]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
