// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/core/application/features/sync/services/sync_device_processing_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:acore/acore.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'package:application/features/sync/models/paginated_sync_data.dart'
    as _i3;
import 'package:application/shared/services/abstraction/i_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedSyncData_0<T1 extends _i1.BaseEntity<dynamic>>
    extends _i2.SmartFake
    implements _i3.PaginatedSyncData<T1> {
  _FakePaginatedSyncData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedList_1<T1> extends _i2.SmartFake
    implements _i1.PaginatedList<T1> {
  _FakePaginatedList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRepository<T extends _i1.BaseEntity<TId>, TId> extends _i2.Mock
    implements _i4.IRepository<T, TId> {
  MockIRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.PaginatedSyncData<T>> getPaginatedSyncData(
    DateTime? lastSyncDate, {
    int? pageIndex = 0,
    int? pageSize = 200,
    String? entityType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPaginatedSyncData,
              [lastSyncDate],
              {
                #pageIndex: pageIndex,
                #pageSize: pageSize,
                #entityType: entityType,
              },
            ),
            returnValue: _i5.Future<_i3.PaginatedSyncData<T>>.value(
              _FakePaginatedSyncData_0<T>(
                this,
                Invocation.method(
                  #getPaginatedSyncData,
                  [lastSyncDate],
                  {
                    #pageIndex: pageIndex,
                    #pageSize: pageSize,
                    #entityType: entityType,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.PaginatedSyncData<T>>);

  @override
  _i5.Future<void> hardDeleteSoftDeleted(DateTime? beforeDate) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteSoftDeleted, [beforeDate]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> truncate() =>
      (super.noSuchMethod(
            Invocation.method(#truncate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i1.PaginatedList<T>> getList(
    int? pageIndex,
    int? pageSize, {
    bool? includeDeleted = false,
    _i1.CustomWhereFilter? customWhereFilter,
    List<_i1.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getList,
              [pageIndex, pageSize],
              {
                #includeDeleted: includeDeleted,
                #customWhereFilter: customWhereFilter,
                #customOrder: customOrder,
              },
            ),
            returnValue: _i5.Future<_i1.PaginatedList<T>>.value(
              _FakePaginatedList_1<T>(
                this,
                Invocation.method(
                  #getList,
                  [pageIndex, pageSize],
                  {
                    #includeDeleted: includeDeleted,
                    #customWhereFilter: customWhereFilter,
                    #customOrder: customOrder,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i1.PaginatedList<T>>);

  @override
  _i5.Future<List<T>> getAll({
    bool? includeDeleted = false,
    _i1.CustomWhereFilter? customWhereFilter,
    List<_i1.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #includeDeleted: includeDeleted,
              #customWhereFilter: customWhereFilter,
              #customOrder: customOrder,
            }),
            returnValue: _i5.Future<List<T>>.value(<T>[]),
          )
          as _i5.Future<List<T>>);

  @override
  _i5.Future<T?> getById(TId? id, {bool? includeDeleted = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getById,
              [id],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<T?> getFirst(
    _i1.CustomWhereFilter? customWhereFilter, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFirst,
              [customWhereFilter],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<void> add(T? item) =>
      (super.noSuchMethod(
            Invocation.method(#add, [item]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> update(T? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(T? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
