// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/infrastructure/mobile/features/notification/mobile_notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i10;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i11;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i13;
import 'package:flutter_local_notifications/src/platform_flutter_local_notifications.dart'
    as _i17;
import 'package:flutter_local_notifications/src/platform_specifics/android/enums.dart'
    as _i20;
import 'package:flutter_local_notifications/src/platform_specifics/android/initialization_settings.dart'
    as _i18;
import 'package:flutter_local_notifications/src/platform_specifics/android/notification_channel.dart'
    as _i22;
import 'package:flutter_local_notifications/src/platform_specifics/android/notification_channel_group.dart'
    as _i21;
import 'package:flutter_local_notifications/src/platform_specifics/android/notification_details.dart'
    as _i19;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i15;
import 'package:flutter_local_notifications/src/platform_specifics/android/styles/messaging_style_information.dart'
    as _i23;
import 'package:flutter_local_notifications/src/types.dart' as _i16;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i12;
import 'package:mediatr/mediatr.dart' as _i4;
import 'package:mediatr/src/internals/i_domain_event.dart' as _i6;
import 'package:mediatr/src/internals/i_event_handler.dart' as _i5;
import 'package:mediatr/src/internals/i_request.dart' as _i7;
import 'package:mediatr/src/internals/i_request_handler.dart' as _i9;
import 'package:mediatr/src/internals/pipeline.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:timezone/timezone.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePipeline_0 extends _i1.SmartFake implements _i2.Pipeline {
  _FakePipeline_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Mediator].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediator extends _i1.Mock implements _i4.Mediator {
  MockMediator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Pipeline get pipeline =>
      (super.noSuchMethod(
            Invocation.getter(#pipeline),
            returnValue: _FakePipeline_0(this, Invocation.getter(#pipeline)),
          )
          as _i2.Pipeline);

  @override
  Map<Type, _i4.HandlerCreator<dynamic>> get handlers =>
      (super.noSuchMethod(
            Invocation.getter(#handlers),
            returnValue: <Type, _i4.HandlerCreator<dynamic>>{},
          )
          as Map<Type, _i4.HandlerCreator<dynamic>>);

  @override
  Map<Type, List<_i5.IEventHandler<_i6.IDomainEvent>>> get eventHandlers =>
      (super.noSuchMethod(
            Invocation.getter(#eventHandlers),
            returnValue: <Type, List<_i5.IEventHandler<_i6.IDomainEvent>>>{},
          )
          as Map<Type, List<_i5.IEventHandler<_i6.IDomainEvent>>>);

  @override
  Map<Type, List<_i4.FuncEventHandler<_i6.IDomainEvent>>>
  get eventFuncHandler =>
      (super.noSuchMethod(
            Invocation.getter(#eventFuncHandler),
            returnValue: <Type, List<_i4.FuncEventHandler<_i6.IDomainEvent>>>{},
          )
          as Map<Type, List<_i4.FuncEventHandler<_i6.IDomainEvent>>>);

  @override
  _i4.UnsubscribeFunc subscribeWithFunc<E extends _i6.IDomainEvent>(
    _i3.FutureOr<void> Function(_i6.IDomainEvent)? func,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeWithFunc, [func]),
            returnValue: () {},
          )
          as _i4.UnsubscribeFunc);

  @override
  void subscribe<E extends _i6.IDomainEvent>(_i5.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#subscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribe<E extends _i6.IDomainEvent>(_i5.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#unsubscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> publish<E extends _i6.IDomainEvent>(E? event) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<R> send<T extends _i7.IRequest<R>, R extends Object?>(
    T? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#send, [request]),
                  ),
                  (R v) => _i3.Future<R>.value(v),
                ) ??
                _FakeFuture_1<R>(this, Invocation.method(#send, [request])),
          )
          as _i3.Future<R>);

  @override
  void registerHandler<
    IR extends _i7.IRequest<R>,
    R,
    H extends _i9.IRequestHandler<IR, R>
  >(_i4.HandlerCreator<H>? creator) => super.noSuchMethod(
    Invocation.method(#registerHandler, [creator]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i10.FlutterLocalNotificationsPlugin {
  MockFlutterLocalNotificationsPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool?> initialize(
    _i11.InitializationSettings? initializationSettings, {
    _i12.DidReceiveNotificationResponseCallback?
    onDidReceiveNotificationResponse,
    _i12.DidReceiveBackgroundNotificationResponseCallback?
    onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initialize,
              [initializationSettings],
              {
                #onDidReceiveNotificationResponse:
                    onDidReceiveNotificationResponse,
                #onDidReceiveBackgroundNotificationResponse:
                    onDidReceiveBackgroundNotificationResponse,
              },
            ),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<_i12.NotificationAppLaunchDetails?>
  getNotificationAppLaunchDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationAppLaunchDetails, []),
            returnValue: _i3.Future<_i12.NotificationAppLaunchDetails?>.value(),
          )
          as _i3.Future<_i12.NotificationAppLaunchDetails?>);

  @override
  _i3.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i13.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #show,
              [id, title, body, notificationDetails],
              {#payload: payload},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancel(int? id, {String? tag}) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [id], {#tag: tag}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllPendingNotifications, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i14.TZDateTime? scheduledDate,
    _i13.NotificationDetails? notificationDetails, {
    required _i15.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i16.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #zonedSchedule,
              [id, title, body, scheduledDate, notificationDetails],
              {
                #androidScheduleMode: androidScheduleMode,
                #payload: payload,
                #matchDateTimeComponents: matchDateTimeComponents,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i12.RepeatInterval? repeatInterval,
    _i13.NotificationDetails? notificationDetails, {
    required _i15.AndroidScheduleMode? androidScheduleMode,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShow,
              [id, title, body, repeatInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i13.NotificationDetails? notificationDetails, {
    _i15.AndroidScheduleMode? androidScheduleMode =
        _i15.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShowWithDuration,
              [id, title, body, repeatDurationInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i12.PendingNotificationRequest>>
  pendingNotificationRequests() =>
      (super.noSuchMethod(
            Invocation.method(#pendingNotificationRequests, []),
            returnValue:
                _i3.Future<List<_i12.PendingNotificationRequest>>.value(
                  <_i12.PendingNotificationRequest>[],
                ),
          )
          as _i3.Future<List<_i12.PendingNotificationRequest>>);

  @override
  _i3.Future<List<_i12.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNotifications, []),
            returnValue: _i3.Future<List<_i12.ActiveNotification>>.value(
              <_i12.ActiveNotification>[],
            ),
          )
          as _i3.Future<List<_i12.ActiveNotification>>);
}

/// A class which mocks [AndroidFlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockAndroidFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i17.AndroidFlutterLocalNotificationsPlugin {
  MockAndroidFlutterLocalNotificationsPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> initialize(
    _i18.AndroidInitializationSettings? initializationSettings, {
    _i12.DidReceiveNotificationResponseCallback?
    onDidReceiveNotificationResponse,
    _i12.DidReceiveBackgroundNotificationResponseCallback?
    onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initialize,
              [initializationSettings],
              {
                #onDidReceiveNotificationResponse:
                    onDidReceiveNotificationResponse,
                #onDidReceiveBackgroundNotificationResponse:
                    onDidReceiveBackgroundNotificationResponse,
              },
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool?> requestExactAlarmsPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestExactAlarmsPermission, []),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> requestFullScreenIntentPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestFullScreenIntentPermission, []),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> requestNotificationsPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestNotificationsPermission, []),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> requestNotificationPolicyAccess() =>
      (super.noSuchMethod(
            Invocation.method(#requestNotificationPolicyAccess, []),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> hasNotificationPolicyAccess() =>
      (super.noSuchMethod(
            Invocation.method(#hasNotificationPolicyAccess, []),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i14.TZDateTime? scheduledDate,
    _i19.AndroidNotificationDetails? notificationDetails, {
    required _i15.AndroidScheduleMode? scheduleMode,
    String? payload,
    _i16.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #zonedSchedule,
              [id, title, body, scheduledDate, notificationDetails],
              {
                #scheduleMode: scheduleMode,
                #payload: payload,
                #matchDateTimeComponents: matchDateTimeComponents,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> startForegroundService(
    int? id,
    String? title,
    String? body, {
    _i19.AndroidNotificationDetails? notificationDetails,
    String? payload,
    _i20.AndroidServiceStartType? startType =
        _i20.AndroidServiceStartType.startSticky,
    Set<_i20.AndroidServiceForegroundType>? foregroundServiceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startForegroundService,
              [id, title, body],
              {
                #notificationDetails: notificationDetails,
                #payload: payload,
                #startType: startType,
                #foregroundServiceTypes: foregroundServiceTypes,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopForegroundService() =>
      (super.noSuchMethod(
            Invocation.method(#stopForegroundService, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> show(
    int? id,
    String? title,
    String? body, {
    _i19.AndroidNotificationDetails? notificationDetails,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #show,
              [id, title, body],
              {#notificationDetails: notificationDetails, #payload: payload},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i12.RepeatInterval? repeatInterval, {
    _i19.AndroidNotificationDetails? notificationDetails,
    String? payload,
    _i15.AndroidScheduleMode? scheduleMode = _i15.AndroidScheduleMode.exact,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShow,
              [id, title, body, repeatInterval],
              {
                #notificationDetails: notificationDetails,
                #payload: payload,
                #scheduleMode: scheduleMode,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval, {
    _i19.AndroidNotificationDetails? notificationDetails,
    String? payload,
    _i15.AndroidScheduleMode? scheduleMode = _i15.AndroidScheduleMode.exact,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShowWithDuration,
              [id, title, body, repeatDurationInterval],
              {
                #notificationDetails: notificationDetails,
                #payload: payload,
                #scheduleMode: scheduleMode,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancel(int? id, {String? tag}) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [id], {#tag: tag}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createNotificationChannelGroup(
    _i21.AndroidNotificationChannelGroup? notificationChannelGroup,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNotificationChannelGroup, [
              notificationChannelGroup,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNotificationChannelGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotificationChannelGroup, [groupId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createNotificationChannel(
    _i22.AndroidNotificationChannel? notificationChannel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNotificationChannel, [
              notificationChannel,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNotificationChannel(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotificationChannel, [channelId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i23.MessagingStyleInformation?>
  getActiveNotificationMessagingStyle(int? id, {String? tag}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getActiveNotificationMessagingStyle,
              [id],
              {#tag: tag},
            ),
            returnValue: _i3.Future<_i23.MessagingStyleInformation?>.value(),
          )
          as _i3.Future<_i23.MessagingStyleInformation?>);

  @override
  _i3.Future<List<_i22.AndroidNotificationChannel>?>
  getNotificationChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationChannels, []),
            returnValue:
                _i3.Future<List<_i22.AndroidNotificationChannel>?>.value(),
          )
          as _i3.Future<List<_i22.AndroidNotificationChannel>?>);

  @override
  _i3.Future<bool?> areNotificationsEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#areNotificationsEnabled, []),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> canScheduleExactNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#canScheduleExactNotifications, []),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllPendingNotifications, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i12.NotificationAppLaunchDetails?>
  getNotificationAppLaunchDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationAppLaunchDetails, []),
            returnValue: _i3.Future<_i12.NotificationAppLaunchDetails?>.value(),
          )
          as _i3.Future<_i12.NotificationAppLaunchDetails?>);

  @override
  _i3.Future<List<_i12.PendingNotificationRequest>>
  pendingNotificationRequests() =>
      (super.noSuchMethod(
            Invocation.method(#pendingNotificationRequests, []),
            returnValue:
                _i3.Future<List<_i12.PendingNotificationRequest>>.value(
                  <_i12.PendingNotificationRequest>[],
                ),
          )
          as _i3.Future<List<_i12.PendingNotificationRequest>>);

  @override
  _i3.Future<List<_i12.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNotifications, []),
            returnValue: _i3.Future<List<_i12.ActiveNotification>>.value(
              <_i12.ActiveNotification>[],
            ),
          )
          as _i3.Future<List<_i12.ActiveNotification>>);
}
