// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/core/application/features/widget/services/widget_service/helpers/widget_data_aggregator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:acore/acore.dart' as _i4;
import 'package:mediatr/mediatr.dart' as _i6;
import 'package:mediatr/src/internals/i_domain_event.dart' as _i8;
import 'package:mediatr/src/internals/i_event_handler.dart' as _i7;
import 'package:mediatr/src/internals/i_request.dart' as _i9;
import 'package:mediatr/src/internals/i_request_handler.dart' as _i11;
import 'package:mediatr/src/internals/pipeline.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:whph/core/application/features/habits/services/i_habit_record_repository.dart'
    as _i13;
import 'package:whph/core/application/features/sync/models/paginated_sync_data.dart'
    as _i5;
import 'package:whph/core/domain/features/habits/habit_record.dart' as _i14;
import 'package:whph/core/domain/features/habits/habit_record_status.dart'
    as _i15;
import 'package:whph/presentation/ui/shared/services/filter_settings_manager.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePipeline_0 extends _i1.SmartFake implements _i2.Pipeline {
  _FakePipeline_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIContainer_2 extends _i1.SmartFake implements _i4.IContainer {
  _FakeIContainer_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedList_3<T> extends _i1.SmartFake
    implements _i4.PaginatedList<T> {
  _FakePaginatedList_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedSyncData_4<T extends _i4.BaseEntity<dynamic>>
    extends _i1.SmartFake
    implements _i5.PaginatedSyncData<T> {
  _FakePaginatedSyncData_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Mediator].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediator extends _i1.Mock implements _i6.Mediator {
  MockMediator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Pipeline get pipeline =>
      (super.noSuchMethod(
            Invocation.getter(#pipeline),
            returnValue: _FakePipeline_0(this, Invocation.getter(#pipeline)),
          )
          as _i2.Pipeline);

  @override
  Map<Type, _i6.HandlerCreator<dynamic>> get handlers =>
      (super.noSuchMethod(
            Invocation.getter(#handlers),
            returnValue: <Type, _i6.HandlerCreator<dynamic>>{},
          )
          as Map<Type, _i6.HandlerCreator<dynamic>>);

  @override
  Map<Type, List<_i7.IEventHandler<_i8.IDomainEvent>>> get eventHandlers =>
      (super.noSuchMethod(
            Invocation.getter(#eventHandlers),
            returnValue: <Type, List<_i7.IEventHandler<_i8.IDomainEvent>>>{},
          )
          as Map<Type, List<_i7.IEventHandler<_i8.IDomainEvent>>>);

  @override
  Map<Type, List<_i6.FuncEventHandler<_i8.IDomainEvent>>>
  get eventFuncHandler =>
      (super.noSuchMethod(
            Invocation.getter(#eventFuncHandler),
            returnValue: <Type, List<_i6.FuncEventHandler<_i8.IDomainEvent>>>{},
          )
          as Map<Type, List<_i6.FuncEventHandler<_i8.IDomainEvent>>>);

  @override
  _i6.UnsubscribeFunc subscribeWithFunc<E extends _i8.IDomainEvent>(
    _i3.FutureOr<void> Function(_i8.IDomainEvent)? func,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeWithFunc, [func]),
            returnValue: () {},
          )
          as _i6.UnsubscribeFunc);

  @override
  void subscribe<E extends _i8.IDomainEvent>(_i7.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#subscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribe<E extends _i8.IDomainEvent>(_i7.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#unsubscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> publish<E extends _i8.IDomainEvent>(E? event) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<R> send<T extends _i9.IRequest<R>, R extends Object?>(
    T? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#send, [request]),
                  ),
                  (R v) => _i3.Future<R>.value(v),
                ) ??
                _FakeFuture_1<R>(this, Invocation.method(#send, [request])),
          )
          as _i3.Future<R>);

  @override
  void registerHandler<
    IR extends _i9.IRequest<R>,
    R,
    H extends _i11.IRequestHandler<IR, R>
  >(_i6.HandlerCreator<H>? creator) => super.noSuchMethod(
    Invocation.method(#registerHandler, [creator]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IContainer].
///
/// See the documentation for Mockito's code generation for more information.
class MockIContainer extends _i1.Mock implements _i4.IContainer {
  MockIContainer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.IContainer get instance =>
      (super.noSuchMethod(
            Invocation.getter(#instance),
            returnValue: _FakeIContainer_2(this, Invocation.getter(#instance)),
          )
          as _i4.IContainer);

  @override
  T resolve<T>() =>
      (super.noSuchMethod(
            Invocation.method(#resolve, []),
            returnValue: _i10.dummyValue<T>(
              this,
              Invocation.method(#resolve, []),
            ),
          )
          as T);

  @override
  void registerSingleton<T>(T Function(_i4.IContainer)? factory) =>
      super.noSuchMethod(
        Invocation.method(#registerSingleton, [factory]),
        returnValueForMissingStub: null,
      );

  @override
  bool isRegistered<T>() =>
      (super.noSuchMethod(
            Invocation.method(#isRegistered, []),
            returnValue: false,
          )
          as bool);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FilterSettingsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterSettingsManager extends _i1.Mock
    implements _i12.FilterSettingsManager {
  MockFilterSettingsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveFilterSettings({
    required String? settingKey,
    required Map<String, dynamic>? filterSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFilterSettings, [], {
              #settingKey: settingKey,
              #filterSettings: filterSettings,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> loadFilterSettings({
    required String? settingKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadFilterSettings, [], {
              #settingKey: settingKey,
            }),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<bool> hasUnsavedChanges({
    required String? settingKey,
    required Map<String, dynamic>? currentSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasUnsavedChanges, [], {
              #settingKey: settingKey,
              #currentSettings: currentSettings,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [IHabitRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHabitRecordRepository extends _i1.Mock
    implements _i13.IHabitRecordRepository {
  MockIHabitRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.PaginatedList<_i14.HabitRecord>> getListByHabitIdAndRangeDate(
    String? habitId,
    DateTime? startDate,
    DateTime? endDate,
    int? pageIndex,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getListByHabitIdAndRangeDate, [
              habitId,
              startDate,
              endDate,
              pageIndex,
              pageSize,
            ]),
            returnValue: _i3.Future<_i4.PaginatedList<_i14.HabitRecord>>.value(
              _FakePaginatedList_3<_i14.HabitRecord>(
                this,
                Invocation.method(#getListByHabitIdAndRangeDate, [
                  habitId,
                  startDate,
                  endDate,
                  pageIndex,
                  pageSize,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.PaginatedList<_i14.HabitRecord>>);

  @override
  _i3.Future<List<_i14.HabitRecord>> getByHabitId(String? habitId) =>
      (super.noSuchMethod(
            Invocation.method(#getByHabitId, [habitId]),
            returnValue: _i3.Future<List<_i14.HabitRecord>>.value(
              <_i14.HabitRecord>[],
            ),
          )
          as _i3.Future<List<_i14.HabitRecord>>);

  @override
  _i3.Future<int> countByHabitIdAndDate(String? habitId, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#countByHabitIdAndDate, [habitId, date]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i14.HabitRecord>> getByHabitIdAndStatus(
    String? habitId,
    _i15.HabitRecordStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByHabitIdAndStatus, [habitId, status]),
            returnValue: _i3.Future<List<_i14.HabitRecord>>.value(
              <_i14.HabitRecord>[],
            ),
          )
          as _i3.Future<List<_i14.HabitRecord>>);

  @override
  _i3.Future<_i5.PaginatedSyncData<_i14.HabitRecord>> getPaginatedSyncData(
    DateTime? lastSyncDate, {
    int? pageIndex = 0,
    int? pageSize = 200,
    String? entityType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPaginatedSyncData,
              [lastSyncDate],
              {
                #pageIndex: pageIndex,
                #pageSize: pageSize,
                #entityType: entityType,
              },
            ),
            returnValue:
                _i3.Future<_i5.PaginatedSyncData<_i14.HabitRecord>>.value(
                  _FakePaginatedSyncData_4<_i14.HabitRecord>(
                    this,
                    Invocation.method(
                      #getPaginatedSyncData,
                      [lastSyncDate],
                      {
                        #pageIndex: pageIndex,
                        #pageSize: pageSize,
                        #entityType: entityType,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i5.PaginatedSyncData<_i14.HabitRecord>>);

  @override
  _i3.Future<void> hardDeleteSoftDeleted(DateTime? beforeDate) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteSoftDeleted, [beforeDate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> truncate() =>
      (super.noSuchMethod(
            Invocation.method(#truncate, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.PaginatedList<_i14.HabitRecord>> getList(
    int? pageIndex,
    int? pageSize, {
    bool? includeDeleted = false,
    _i4.CustomWhereFilter? customWhereFilter,
    List<_i4.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getList,
              [pageIndex, pageSize],
              {
                #includeDeleted: includeDeleted,
                #customWhereFilter: customWhereFilter,
                #customOrder: customOrder,
              },
            ),
            returnValue: _i3.Future<_i4.PaginatedList<_i14.HabitRecord>>.value(
              _FakePaginatedList_3<_i14.HabitRecord>(
                this,
                Invocation.method(
                  #getList,
                  [pageIndex, pageSize],
                  {
                    #includeDeleted: includeDeleted,
                    #customWhereFilter: customWhereFilter,
                    #customOrder: customOrder,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i4.PaginatedList<_i14.HabitRecord>>);

  @override
  _i3.Future<List<_i14.HabitRecord>> getAll({
    bool? includeDeleted = false,
    _i4.CustomWhereFilter? customWhereFilter,
    List<_i4.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #includeDeleted: includeDeleted,
              #customWhereFilter: customWhereFilter,
              #customOrder: customOrder,
            }),
            returnValue: _i3.Future<List<_i14.HabitRecord>>.value(
              <_i14.HabitRecord>[],
            ),
          )
          as _i3.Future<List<_i14.HabitRecord>>);

  @override
  _i3.Future<_i14.HabitRecord?> getById(
    String? id, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getById,
              [id],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i3.Future<_i14.HabitRecord?>.value(),
          )
          as _i3.Future<_i14.HabitRecord?>);

  @override
  _i3.Future<_i14.HabitRecord?> getFirst(
    _i4.CustomWhereFilter? customWhereFilter, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFirst,
              [customWhereFilter],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i3.Future<_i14.HabitRecord?>.value(),
          )
          as _i3.Future<_i14.HabitRecord?>);

  @override
  _i3.Future<void> add(_i14.HabitRecord? item) =>
      (super.noSuchMethod(
            Invocation.method(#add, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i14.HabitRecord? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(_i14.HabitRecord? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
