name: "Initialize Submodules"
description: "Initializes required submodules for the project"

inputs:
  include-flatpak:
    description: "Whether to initialize Flatpak-related submodules"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Initialize acore submodule
      shell: bash
      run: |
        echo "Initializing acore submodule..."

        # Clean any potential submodule issues first
        git submodule sync || echo "Submodule sync not needed"

        # Initialize the acore submodule
        if git submodule update --init --recursive packages/acore-flutter packages/acore-scripts; then
          echo "✅ ACore submodules initialized successfully"
        else
          echo "❌ Failed to initialize acore submodules"
          exit 1
        fi

        # Initialize Flatpak submodules if requested
        if [[ "${{ inputs.include-flatpak }}" == "true" ]]; then
          echo "📦 Initializing Flatpak submodules..."
          if git submodule update --init --recursive packaging/flatpak/flatpak-flutter packaging/flatpak/flathub packaging/flatpak/shared-modules; then
            echo "✅ Flatpak submodules initialized successfully"
          else
            echo "❌ Failed to initialize Flatpak submodules"
            exit 1
          fi
        fi

        # Verify the submodule was initialized correctly
        if [[ -d "packages/acore-flutter" && -f "packages/acore-flutter/pubspec.yaml" ]]; then
          echo "✅ acore-flutter verification passed"
        else
          echo "❌ acore-flutter verification failed"
          exit 1
        fi

        if [[ ! -d "packages/acore-scripts" ]]; then
           echo "❌ acore-scripts verification failed"
           exit 1
        fi
