// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/presentation/ui/features/notifications/services/reminder_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i13;

import 'package:flutter/material.dart' as _i4;
import 'package:mediatr/mediatr.dart' as _i6;
import 'package:mediatr/src/internals/i_domain_event.dart' as _i8;
import 'package:mediatr/src/internals/i_event_handler.dart' as _i7;
import 'package:mediatr/src/internals/i_request.dart' as _i9;
import 'package:mediatr/src/internals/i_request_handler.dart' as _i11;
import 'package:mediatr/src/internals/pipeline.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:whph/core/application/features/tasks/services/abstraction/i_reminder_calculation_service.dart'
    as _i17;
import 'package:whph/core/domain/features/tasks/task.dart' as _i18;
import 'package:whph/infrastructure/shared/features/notification/abstractions/i_notification_payload_handler.dart'
    as _i16;
import 'package:whph/presentation/ui/features/habits/services/habits_service.dart'
    as _i14;
import 'package:whph/presentation/ui/features/tasks/services/tasks_service.dart'
    as _i12;
import 'package:whph/presentation/ui/shared/services/abstraction/i_reminder_service.dart'
    as _i5;
import 'package:whph/presentation/ui/shared/services/abstraction/i_translation_service.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePipeline_0 extends _i1.SmartFake implements _i2.Pipeline {
  _FakePipeline_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_3 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [IReminderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReminderService extends _i1.Mock implements _i5.IReminderService {
  MockIReminderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleReminder({
    required String? id,
    required String? title,
    required String? body,
    required DateTime? scheduledDate,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleReminder, [], {
              #id: id,
              #title: title,
              #body: body,
              #scheduledDate: scheduledDate,
              #payload: payload,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleRecurringReminder({
    required String? id,
    required String? title,
    required String? body,
    required _i4.TimeOfDay? time,
    required List<int>? days,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleRecurringReminder, [], {
              #id: id,
              #title: title,
              #body: body,
              #time: time,
              #days: days,
              #payload: payload,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelReminder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelReminder, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelReminders({
    bool Function(String)? idFilter,
    String? startsWith,
    String? contains,
    String? equals,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelReminders, [], {
              #idFilter: idFilter,
              #startsWith: startsWith,
              #contains: contains,
              #equals: equals,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllReminders() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllReminders, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> onBootCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#onBootCompleted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [Mediator].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediator extends _i1.Mock implements _i6.Mediator {
  MockMediator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Pipeline get pipeline =>
      (super.noSuchMethod(
            Invocation.getter(#pipeline),
            returnValue: _FakePipeline_0(this, Invocation.getter(#pipeline)),
          )
          as _i2.Pipeline);

  @override
  Map<Type, _i6.HandlerCreator<dynamic>> get handlers =>
      (super.noSuchMethod(
            Invocation.getter(#handlers),
            returnValue: <Type, _i6.HandlerCreator<dynamic>>{},
          )
          as Map<Type, _i6.HandlerCreator<dynamic>>);

  @override
  Map<Type, List<_i7.IEventHandler<_i8.IDomainEvent>>> get eventHandlers =>
      (super.noSuchMethod(
            Invocation.getter(#eventHandlers),
            returnValue: <Type, List<_i7.IEventHandler<_i8.IDomainEvent>>>{},
          )
          as Map<Type, List<_i7.IEventHandler<_i8.IDomainEvent>>>);

  @override
  Map<Type, List<_i6.FuncEventHandler<_i8.IDomainEvent>>>
  get eventFuncHandler =>
      (super.noSuchMethod(
            Invocation.getter(#eventFuncHandler),
            returnValue: <Type, List<_i6.FuncEventHandler<_i8.IDomainEvent>>>{},
          )
          as Map<Type, List<_i6.FuncEventHandler<_i8.IDomainEvent>>>);

  @override
  _i6.UnsubscribeFunc subscribeWithFunc<E extends _i8.IDomainEvent>(
    _i3.FutureOr<void> Function(_i8.IDomainEvent)? func,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeWithFunc, [func]),
            returnValue: () {},
          )
          as _i6.UnsubscribeFunc);

  @override
  void subscribe<E extends _i8.IDomainEvent>(_i7.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#subscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribe<E extends _i8.IDomainEvent>(_i7.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#unsubscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> publish<E extends _i8.IDomainEvent>(E? event) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<R> send<T extends _i9.IRequest<R>, R extends Object?>(
    T? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#send, [request]),
                  ),
                  (R v) => _i3.Future<R>.value(v),
                ) ??
                _FakeFuture_1<R>(this, Invocation.method(#send, [request])),
          )
          as _i3.Future<R>);

  @override
  void registerHandler<
    IR extends _i9.IRequest<R>,
    R,
    H extends _i11.IRequestHandler<IR, R>
  >(_i6.HandlerCreator<H>? creator) => super.noSuchMethod(
    Invocation.method(#registerHandler, [creator]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TasksService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksService extends _i1.Mock implements _i12.TasksService {
  MockTasksService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ValueNotifier<String?> get onTaskCreated =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskCreated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskCreated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTaskUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskUpdated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskUpdated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTaskDeleted =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskDeleted),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskDeleted),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTaskTimeRecordUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskTimeRecordUpdated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskTimeRecordUpdated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTaskCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskCompleted),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskCompleted),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void notifyTaskCreated(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskCreated, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTaskUpdated(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskUpdated, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTaskDeleted(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskDeleted, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTaskTimeRecordUpdated(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskTimeRecordUpdated, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTaskCompleted(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskCompleted, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HabitsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitsService extends _i1.Mock implements _i14.HabitsService {
  MockHabitsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ValueNotifier<String?> get onHabitCreated =>
      (super.noSuchMethod(
            Invocation.getter(#onHabitCreated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onHabitCreated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onHabitUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onHabitUpdated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onHabitUpdated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onHabitDeleted =>
      (super.noSuchMethod(
            Invocation.getter(#onHabitDeleted),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onHabitDeleted),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onHabitRecordAdded =>
      (super.noSuchMethod(
            Invocation.getter(#onHabitRecordAdded),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onHabitRecordAdded),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onHabitRecordRemoved =>
      (super.noSuchMethod(
            Invocation.getter(#onHabitRecordRemoved),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onHabitRecordRemoved),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void notifyHabitCreated(String? habitId) => super.noSuchMethod(
    Invocation.method(#notifyHabitCreated, [habitId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyHabitUpdated(String? habitId) => super.noSuchMethod(
    Invocation.method(#notifyHabitUpdated, [habitId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyHabitDeleted(String? habitId) => super.noSuchMethod(
    Invocation.method(#notifyHabitDeleted, [habitId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyHabitRecordAdded(String? habitId) => super.noSuchMethod(
    Invocation.method(#notifyHabitRecordAdded, [habitId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyHabitRecordRemoved(String? habitId) => super.noSuchMethod(
    Invocation.method(#notifyHabitRecordRemoved, [habitId]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ITranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITranslationService extends _i1.Mock
    implements _i15.ITranslationService {
  MockITranslationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String translate(String? key, {Map<String, String>? namedArgs}) =>
      (super.noSuchMethod(
            Invocation.method(#translate, [key], {#namedArgs: namedArgs}),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#translate, [key], {#namedArgs: namedArgs}),
            ),
          )
          as String);

  @override
  _i3.Future<void> changeLanguage(
    _i4.BuildContext? context,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [context, languageCode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> changeLanguageWithoutNavigation(
    _i4.BuildContext? context,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguageWithoutNavigation, [
              context,
              languageCode,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String getCurrentLanguage(_i4.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLanguage, [context]),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#getCurrentLanguage, [context]),
            ),
          )
          as String);

  @override
  _i4.Widget wrapWithTranslations(_i4.Widget? child) =>
      (super.noSuchMethod(
            Invocation.method(#wrapWithTranslations, [child]),
            returnValue: _FakeWidget_3(
              this,
              Invocation.method(#wrapWithTranslations, [child]),
            ),
          )
          as _i4.Widget);
}

/// A class which mocks [INotificationPayloadHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockINotificationPayloadHandler extends _i1.Mock
    implements _i16.INotificationPayloadHandler {
  MockINotificationPayloadHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> handlePayload(String? payload) =>
      (super.noSuchMethod(
            Invocation.method(#handlePayload, [payload]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String createNavigationPayload({
    required String? route,
    Map<String, dynamic>? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNavigationPayload, [], {
              #route: route,
              #arguments: arguments,
            }),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#createNavigationPayload, [], {
                #route: route,
                #arguments: arguments,
              }),
            ),
          )
          as String);
}

/// A class which mocks [IReminderCalculationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReminderCalculationService extends _i1.Mock
    implements _i17.IReminderCalculationService {
  MockIReminderCalculationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime? calculateReminderDateTime({
    required DateTime? baseDate,
    required _i18.ReminderTime? reminderTime,
    int? customOffset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateReminderDateTime, [], {
              #baseDate: baseDate,
              #reminderTime: reminderTime,
              #customOffset: customOffset,
            }),
          )
          as DateTime?);

  @override
  bool validateReminderSettings({
    required _i18.ReminderTime? reminderTime,
    int? customOffset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateReminderSettings, [], {
              #reminderTime: reminderTime,
              #customOffset: customOffset,
            }),
            returnValue: false,
          )
          as bool);

  @override
  DateTime? getNextReminderOccurrence({
    required _i18.Task? task,
    DateTime? afterDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNextReminderOccurrence, [], {
              #task: task,
              #afterDate: afterDate,
            }),
          )
          as DateTime?);

  @override
  bool shouldReminderTrigger({
    required _i18.Task? task,
    required DateTime? currentTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shouldReminderTrigger, [], {
              #task: task,
              #currentTime: currentTime,
            }),
            returnValue: false,
          )
          as bool);
}
