// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/core/application/features/tasks/commands/remove_task_tag_command_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:acore/acore.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'package:application/features/sync/models/paginated_sync_data.dart'
    as _i3;
import 'package:application/features/tags/models/tag_time_data.dart'
    as _i7;
import 'package:application/features/tasks/services/abstraction/i_task_tag_repository.dart'
    as _i4;
import 'package:domain/features/tasks/task_tag.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedSyncData_0<T extends _i1.BaseEntity<dynamic>>
    extends _i2.SmartFake
    implements _i3.PaginatedSyncData<T> {
  _FakePaginatedSyncData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedList_1<T> extends _i2.SmartFake
    implements _i1.PaginatedList<T> {
  _FakePaginatedList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ITaskTagRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskTagRepository extends _i2.Mock
    implements _i4.ITaskTagRepository {
  MockITaskTagRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> anyByTaskIdAndTagId(String? taskId, String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#anyByTaskIdAndTagId, [taskId, tagId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i6.TaskTag>> getByTaskId(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getByTaskId, [taskId]),
            returnValue: _i5.Future<List<_i6.TaskTag>>.value(<_i6.TaskTag>[]),
          )
          as _i5.Future<List<_i6.TaskTag>>);

  @override
  _i5.Future<List<_i6.TaskTag>> getByTagId(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#getByTagId, [tagId]),
            returnValue: _i5.Future<List<_i6.TaskTag>>.value(<_i6.TaskTag>[]),
          )
          as _i5.Future<List<_i6.TaskTag>>);

  @override
  _i5.Future<List<_i7.TagTimeData>> getTopTagsByDuration(
    DateTime? startDate,
    DateTime? endDate, {
    int? limit,
    List<String>? filterByTags,
    bool? filterByIsArchived = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTopTagsByDuration,
              [startDate, endDate],
              {
                #limit: limit,
                #filterByTags: filterByTags,
                #filterByIsArchived: filterByIsArchived,
              },
            ),
            returnValue: _i5.Future<List<_i7.TagTimeData>>.value(
              <_i7.TagTimeData>[],
            ),
          )
          as _i5.Future<List<_i7.TagTimeData>>);

  @override
  _i5.Future<void> updateTagOrders(
    String? taskId,
    Map<String, int>? tagOrders,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTagOrders, [taskId, tagOrders]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.PaginatedSyncData<_i6.TaskTag>> getPaginatedSyncData(
    DateTime? lastSyncDate, {
    int? pageIndex = 0,
    int? pageSize = 200,
    String? entityType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPaginatedSyncData,
              [lastSyncDate],
              {
                #pageIndex: pageIndex,
                #pageSize: pageSize,
                #entityType: entityType,
              },
            ),
            returnValue: _i5.Future<_i3.PaginatedSyncData<_i6.TaskTag>>.value(
              _FakePaginatedSyncData_0<_i6.TaskTag>(
                this,
                Invocation.method(
                  #getPaginatedSyncData,
                  [lastSyncDate],
                  {
                    #pageIndex: pageIndex,
                    #pageSize: pageSize,
                    #entityType: entityType,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.PaginatedSyncData<_i6.TaskTag>>);

  @override
  _i5.Future<void> hardDeleteSoftDeleted(DateTime? beforeDate) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteSoftDeleted, [beforeDate]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> truncate() =>
      (super.noSuchMethod(
            Invocation.method(#truncate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i1.PaginatedList<_i6.TaskTag>> getList(
    int? pageIndex,
    int? pageSize, {
    bool? includeDeleted = false,
    _i1.CustomWhereFilter? customWhereFilter,
    List<_i1.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getList,
              [pageIndex, pageSize],
              {
                #includeDeleted: includeDeleted,
                #customWhereFilter: customWhereFilter,
                #customOrder: customOrder,
              },
            ),
            returnValue: _i5.Future<_i1.PaginatedList<_i6.TaskTag>>.value(
              _FakePaginatedList_1<_i6.TaskTag>(
                this,
                Invocation.method(
                  #getList,
                  [pageIndex, pageSize],
                  {
                    #includeDeleted: includeDeleted,
                    #customWhereFilter: customWhereFilter,
                    #customOrder: customOrder,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i1.PaginatedList<_i6.TaskTag>>);

  @override
  _i5.Future<List<_i6.TaskTag>> getAll({
    bool? includeDeleted = false,
    _i1.CustomWhereFilter? customWhereFilter,
    List<_i1.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #includeDeleted: includeDeleted,
              #customWhereFilter: customWhereFilter,
              #customOrder: customOrder,
            }),
            returnValue: _i5.Future<List<_i6.TaskTag>>.value(<_i6.TaskTag>[]),
          )
          as _i5.Future<List<_i6.TaskTag>>);

  @override
  _i5.Future<_i6.TaskTag?> getById(
    String? id, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getById,
              [id],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i5.Future<_i6.TaskTag?>.value(),
          )
          as _i5.Future<_i6.TaskTag?>);

  @override
  _i5.Future<_i6.TaskTag?> getFirst(
    _i1.CustomWhereFilter? customWhereFilter, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFirst,
              [customWhereFilter],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i5.Future<_i6.TaskTag?>.value(),
          )
          as _i5.Future<_i6.TaskTag?>);

  @override
  _i5.Future<void> add(_i6.TaskTag? item) =>
      (super.noSuchMethod(
            Invocation.method(#add, [item]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> update(_i6.TaskTag? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(_i6.TaskTag? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
