// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/core/application/features/sync/commands/paginated_sync_command_bidirectional_progress_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:acore/acore.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:whph/core/application/features/sync/models/paginated_sync_data.dart'
    as _i3;
import 'package:whph/core/application/features/sync/models/paginated_sync_data_dto.dart'
    as _i10;
import 'package:whph/core/application/features/sync/models/sync_data.dart'
    as _i14;
import 'package:whph/core/application/features/sync/services/abstraction/i_sync_communication_service.dart'
    as _i4;
import 'package:whph/core/application/features/sync/services/abstraction/i_sync_configuration_service.dart'
    as _i8;
import 'package:whph/core/application/features/sync/services/abstraction/i_sync_data_processing_service.dart'
    as _i13;
import 'package:whph/core/application/features/sync/services/abstraction/i_sync_device_repository.dart'
    as _i5;
import 'package:whph/core/application/features/sync/services/abstraction/i_sync_pagination_service.dart'
    as _i16;
import 'package:whph/core/application/features/sync/services/abstraction/i_sync_validation_service.dart'
    as _i9;
import 'package:whph/core/application/shared/models/websocket_request.dart'
    as _i11;
import 'package:whph/core/application/shared/services/abstraction/i_repository.dart'
    as _i15;
import 'package:whph/core/domain/features/sync/sync_device.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedSyncData_0<T extends _i1.BaseEntity<dynamic>>
    extends _i2.SmartFake implements _i3.PaginatedSyncData<T> {
  _FakePaginatedSyncData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedList_1<T> extends _i2.SmartFake
    implements _i1.PaginatedList<T> {
  _FakePaginatedList_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncCommunicationResponse_2 extends _i2.SmartFake
    implements _i4.SyncCommunicationResponse {
  _FakeSyncCommunicationResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ISyncDeviceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncDeviceRepository extends _i2.Mock
    implements _i5.ISyncDeviceRepository {
  @override
  _i6.Future<_i7.SyncDevice?> getByFromToIp(
    String? fromIp,
    String? toIp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByFromToIp,
          [
            fromIp,
            toIp,
          ],
        ),
        returnValue: _i6.Future<_i7.SyncDevice?>.value(),
        returnValueForMissingStub: _i6.Future<_i7.SyncDevice?>.value(),
      ) as _i6.Future<_i7.SyncDevice?>);

  @override
  _i6.Future<_i3.PaginatedSyncData<_i7.SyncDevice>> getPaginatedSyncData(
    DateTime? lastSyncDate, {
    int? pageIndex = 0,
    int? pageSize = 200,
    String? entityType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginatedSyncData,
          [lastSyncDate],
          {
            #pageIndex: pageIndex,
            #pageSize: pageSize,
            #entityType: entityType,
          },
        ),
        returnValue: _i6.Future<_i3.PaginatedSyncData<_i7.SyncDevice>>.value(
            _FakePaginatedSyncData_0<_i7.SyncDevice>(
          this,
          Invocation.method(
            #getPaginatedSyncData,
            [lastSyncDate],
            {
              #pageIndex: pageIndex,
              #pageSize: pageSize,
              #entityType: entityType,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.PaginatedSyncData<_i7.SyncDevice>>.value(
                _FakePaginatedSyncData_0<_i7.SyncDevice>(
          this,
          Invocation.method(
            #getPaginatedSyncData,
            [lastSyncDate],
            {
              #pageIndex: pageIndex,
              #pageSize: pageSize,
              #entityType: entityType,
            },
          ),
        )),
      ) as _i6.Future<_i3.PaginatedSyncData<_i7.SyncDevice>>);

  @override
  _i6.Future<void> hardDeleteSoftDeleted(DateTime? beforeDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSoftDeleted,
          [beforeDate],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> truncate() => (super.noSuchMethod(
        Invocation.method(
          #truncate,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i1.PaginatedList<_i7.SyncDevice>> getList(
    int? pageIndex,
    int? pageSize, {
    bool? includeDeleted = false,
    _i1.CustomWhereFilter? customWhereFilter,
    List<_i1.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getList,
          [
            pageIndex,
            pageSize,
          ],
          {
            #includeDeleted: includeDeleted,
            #customWhereFilter: customWhereFilter,
            #customOrder: customOrder,
          },
        ),
        returnValue: _i6.Future<_i1.PaginatedList<_i7.SyncDevice>>.value(
            _FakePaginatedList_1<_i7.SyncDevice>(
          this,
          Invocation.method(
            #getList,
            [
              pageIndex,
              pageSize,
            ],
            {
              #includeDeleted: includeDeleted,
              #customWhereFilter: customWhereFilter,
              #customOrder: customOrder,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i1.PaginatedList<_i7.SyncDevice>>.value(
                _FakePaginatedList_1<_i7.SyncDevice>(
          this,
          Invocation.method(
            #getList,
            [
              pageIndex,
              pageSize,
            ],
            {
              #includeDeleted: includeDeleted,
              #customWhereFilter: customWhereFilter,
              #customOrder: customOrder,
            },
          ),
        )),
      ) as _i6.Future<_i1.PaginatedList<_i7.SyncDevice>>);

  @override
  _i6.Future<List<_i7.SyncDevice>> getAll({
    bool? includeDeleted = false,
    _i1.CustomWhereFilter? customWhereFilter,
    List<_i1.CustomOrder>? customOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #includeDeleted: includeDeleted,
            #customWhereFilter: customWhereFilter,
            #customOrder: customOrder,
          },
        ),
        returnValue: _i6.Future<List<_i7.SyncDevice>>.value(<_i7.SyncDevice>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i7.SyncDevice>>.value(<_i7.SyncDevice>[]),
      ) as _i6.Future<List<_i7.SyncDevice>>);

  @override
  _i6.Future<_i7.SyncDevice?> getById(
    String? id, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
          {#includeDeleted: includeDeleted},
        ),
        returnValue: _i6.Future<_i7.SyncDevice?>.value(),
        returnValueForMissingStub: _i6.Future<_i7.SyncDevice?>.value(),
      ) as _i6.Future<_i7.SyncDevice?>);

  @override
  _i6.Future<_i7.SyncDevice?> getFirst(
    _i1.CustomWhereFilter? customWhereFilter, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFirst,
          [customWhereFilter],
          {#includeDeleted: includeDeleted},
        ),
        returnValue: _i6.Future<_i7.SyncDevice?>.value(),
        returnValueForMissingStub: _i6.Future<_i7.SyncDevice?>.value(),
      ) as _i6.Future<_i7.SyncDevice?>);

  @override
  _i6.Future<void> add(_i7.SyncDevice? item) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [item],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> update(_i7.SyncDevice? item) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [item],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> delete(_i7.SyncDevice? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ISyncConfigurationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncConfigurationService extends _i2.Mock
    implements _i8.ISyncConfigurationService {
  @override
  List<_i8.PaginatedSyncConfig<_i1.BaseEntity<String>>>
      getAllConfigurations() => (super.noSuchMethod(
            Invocation.method(
              #getAllConfigurations,
              [],
            ),
            returnValue: <_i8.PaginatedSyncConfig<_i1.BaseEntity<String>>>[],
            returnValueForMissingStub: <_i8
                .PaginatedSyncConfig<_i1.BaseEntity<String>>>[],
          ) as List<_i8.PaginatedSyncConfig<_i1.BaseEntity<String>>>);

  @override
  _i8.PaginatedSyncConfig<_i1.BaseEntity<String>>? getConfiguration(
          String? entityType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConfiguration,
          [entityType],
        ),
        returnValueForMissingStub: null,
      ) as _i8.PaginatedSyncConfig<_i1.BaseEntity<String>>?);

  @override
  _i8.PaginatedSyncConfig<T>?
      getTypedConfiguration<T extends _i1.BaseEntity<String>>(
              String? entityType) =>
          (super.noSuchMethod(
            Invocation.method(
              #getTypedConfiguration,
              [entityType],
            ),
            returnValueForMissingStub: null,
          ) as _i8.PaginatedSyncConfig<T>?);

  @override
  void registerConfiguration<T extends _i1.BaseEntity<String>>(
          _i8.PaginatedSyncConfig<T>? config) =>
      super.noSuchMethod(
        Invocation.method(
          #registerConfiguration,
          [config],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getEntityTypeNames() => (super.noSuchMethod(
        Invocation.method(
          #getEntityTypeNames,
          [],
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool hasEntityType(String? entityType) => (super.noSuchMethod(
        Invocation.method(
          #hasEntityType,
          [entityType],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [ISyncValidationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncValidationService extends _i2.Mock
    implements _i9.ISyncValidationService {
  @override
  _i6.Future<void> validateVersion(String? remoteVersion) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateVersion,
          [remoteVersion],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> validateDeviceId(_i7.SyncDevice? remoteDevice) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateDeviceId,
          [remoteDevice],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void validateEnvironmentMode(_i10.PaginatedSyncDataDto? dto) =>
      super.noSuchMethod(
        Invocation.method(
          #validateEnvironmentMode,
          [dto],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool validateSyncDataIntegrity(_i10.PaginatedSyncDataDto? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateSyncDataIntegrity,
          [dto],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> validateSyncPrerequisites() => (super.noSuchMethod(
        Invocation.method(
          #validateSyncPrerequisites,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ISyncCommunicationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncCommunicationService extends _i2.Mock
    implements _i4.ISyncCommunicationService {
  @override
  _i6.Future<_i4.SyncCommunicationResponse> sendPaginatedDataToDevice(
    String? ipAddress,
    _i10.PaginatedSyncDataDto? dto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPaginatedDataToDevice,
          [
            ipAddress,
            dto,
          ],
        ),
        returnValue: _i6.Future<_i4.SyncCommunicationResponse>.value(
            _FakeSyncCommunicationResponse_2(
          this,
          Invocation.method(
            #sendPaginatedDataToDevice,
            [
              ipAddress,
              dto,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.SyncCommunicationResponse>.value(
                _FakeSyncCommunicationResponse_2(
          this,
          Invocation.method(
            #sendPaginatedDataToDevice,
            [
              ipAddress,
              dto,
            ],
          ),
        )),
      ) as _i6.Future<_i4.SyncCommunicationResponse>);

  @override
  _i6.Future<Map<String, dynamic>> convertDtoToJson(
          _i10.PaginatedSyncDataDto? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertDtoToJson,
          [dto],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<String> serializeMessage(_i11.WebSocketMessage? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #serializeMessage,
          [message],
        ),
        returnValue: _i6.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #serializeMessage,
            [message],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #serializeMessage,
            [message],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<bool> isDeviceReachable(String? ipAddress) => (super.noSuchMethod(
        Invocation.method(
          #isDeviceReachable,
          [ipAddress],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  String getWebSocketUrl(String? ipAddress) => (super.noSuchMethod(
        Invocation.method(
          #getWebSocketUrl,
          [ipAddress],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getWebSocketUrl,
            [ipAddress],
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getWebSocketUrl,
            [ipAddress],
          ),
        ),
      ) as String);

  @override
  _i6.Future<bool> handleConnectionError(
    String? ipAddress,
    Exception? error,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleConnectionError,
          [
            ipAddress,
            error,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [ISyncDataProcessingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncDataProcessingService extends _i2.Mock
    implements _i13.ISyncDataProcessingService {
  @override
  _i6.Future<int> processSyncDataBatch<T extends _i1.BaseEntity<String>>(
    _i14.SyncData<T>? syncData,
    _i15.IRepository<T, String>? repository,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processSyncDataBatch,
          [
            syncData,
            repository,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> processSyncDataBatchDynamic(
    _i14.SyncData<_i1.BaseEntity<dynamic>>? syncData,
    _i15.IRepository<_i1.BaseEntity<dynamic>, dynamic>? repository,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processSyncDataBatchDynamic,
          [
            syncData,
            repository,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int>
      processItemsWithMaximumYielding<T extends _i1.BaseEntity<String>>(
    List<T>? items,
    _i15.IRepository<T, String>? repository,
    String? operationType,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #processItemsWithMaximumYielding,
              [
                items,
                repository,
                operationType,
              ],
            ),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          ) as _i6.Future<int>);

  @override
  _i6.Future<int>
      processSingleItemWithMaximumYielding<T extends _i1.BaseEntity<String>>(
    T? item,
    _i15.IRepository<T, String>? repository,
    String? operationType,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #processSingleItemWithMaximumYielding,
              [
                item,
                repository,
                operationType,
              ],
            ),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          ) as _i6.Future<int>);

  @override
  _i6.Future<T?>
      checkForRecurringTaskDuplicate<T extends _i1.BaseEntity<String>>(
    T? entity,
    _i15.IRepository<T, String>? repository,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #checkForRecurringTaskDuplicate,
              [
                entity,
                repository,
              ],
            ),
            returnValue: _i6.Future<T?>.value(),
            returnValueForMissingStub: _i6.Future<T?>.value(),
          ) as _i6.Future<T?>);

  @override
  bool validateEntityForProcessing<T extends _i1.BaseEntity<String>>(
          T? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateEntityForProcessing,
          [entity],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> cleanupSoftDeletedData(DateTime? oldestLastSyncDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupSoftDeletedData,
          [oldestLastSyncDate],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> yieldToUIThread() => (super.noSuchMethod(
        Invocation.method(
          #yieldToUIThread,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ISyncPaginationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncPaginationService extends _i2.Mock
    implements _i16.ISyncPaginationService {
  @override
  _i6.Stream<_i3.SyncProgress> get progressStream => (super.noSuchMethod(
        Invocation.getter(#progressStream),
        returnValue: _i6.Stream<_i3.SyncProgress>.empty(),
        returnValueForMissingStub: _i6.Stream<_i3.SyncProgress>.empty(),
      ) as _i6.Stream<_i3.SyncProgress>);

  @override
  bool get isSyncInProgress => (super.noSuchMethod(
        Invocation.getter(#isSyncInProgress),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<String> get activeEntityTypes => (super.noSuchMethod(
        Invocation.getter(#activeEntityTypes),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  _i6.Future<bool> syncEntityWithPagination(
    _i8.PaginatedSyncConfig<_i1.BaseEntity<String>>? config,
    _i7.SyncDevice? syncDevice,
    DateTime? lastSyncDate, {
    String? targetDeviceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncEntityWithPagination,
          [
            config,
            syncDevice,
            lastSyncDate,
          ],
          {#targetDeviceId: targetDeviceId},
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  void updateProgress({
    required String? currentEntity,
    required int? currentPage,
    required int? totalPages,
    required double? progressPercentage,
    required int? entitiesCompleted,
    required int? totalEntities,
    required String? operation,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateProgress,
          [],
          {
            #currentEntity: currentEntity,
            #currentPage: currentPage,
            #totalPages: totalPages,
            #progressPercentage: progressPercentage,
            #entitiesCompleted: entitiesCompleted,
            #totalEntities: totalEntities,
            #operation: operation,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetProgress() => super.noSuchMethod(
        Invocation.method(
          #resetProgress,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.SyncProgress? getCurrentProgress(String? entityType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentProgress,
          [entityType],
        ),
        returnValueForMissingStub: null,
      ) as _i3.SyncProgress?);

  @override
  Map<String, int> getServerPaginationMetadata(String? entityType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServerPaginationMetadata,
          [entityType],
        ),
        returnValue: <String, int>{},
        returnValueForMissingStub: <String, int>{},
      ) as Map<String, int>);

  @override
  void updateServerPaginationMetadata(
    String? entityType,
    int? totalPages,
    int? totalItems,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateServerPaginationMetadata,
          [
            entityType,
            totalPages,
            totalItems,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double calculateOverallProgress() => (super.noSuchMethod(
        Invocation.method(
          #calculateOverallProgress,
          [],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i6.Future<void> cancelSync() => (super.noSuchMethod(
        Invocation.method(
          #cancelSync,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  Map<String, _i10.PaginatedSyncDataDto> getPendingResponseData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingResponseData,
          [],
        ),
        returnValue: <String, _i10.PaginatedSyncDataDto>{},
        returnValueForMissingStub: <String, _i10.PaginatedSyncDataDto>{},
      ) as Map<String, _i10.PaginatedSyncDataDto>);

  @override
  void clearPendingResponseData() => super.noSuchMethod(
        Invocation.method(
          #clearPendingResponseData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getLastSentServerPage(
    String? deviceId,
    String? entityType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastSentServerPage,
          [
            deviceId,
            entityType,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setLastSentServerPage(
    String? deviceId,
    String? entityType,
    int? page,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLastSentServerPage,
          [
            deviceId,
            entityType,
            page,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
