// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/presentation/ui/features/tasks/components/task_details_content/controllers/task_details_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i13;

import 'package:acore/acore.dart' as _i17;
import 'package:flutter/foundation.dart' as _i4;
import 'package:flutter/widgets.dart' as _i5;
import 'package:mediatr/mediatr.dart' as _i6;
import 'package:mediatr/src/internals/i_domain_event.dart' as _i8;
import 'package:mediatr/src/internals/i_event_handler.dart' as _i7;
import 'package:mediatr/src/internals/i_request.dart' as _i9;
import 'package:mediatr/src/internals/i_request_handler.dart' as _i11;
import 'package:mediatr/src/internals/pipeline.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:application/features/tasks/services/abstraction/i_task_recurrence_service.dart'
    as _i15;
import 'package:domain/features/tasks/task.dart' as _i16;
import 'package:whph/presentation/ui/features/tags/services/tags_service.dart'
    as _i18;
import 'package:whph/presentation/ui/features/tasks/services/tasks_service.dart'
    as _i12;
import 'package:whph/presentation/ui/shared/services/abstraction/i_translation_service.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePipeline_0 extends _i1.SmartFake implements _i2.Pipeline {
  _FakePipeline_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_3 extends _i1.SmartFake implements _i5.Widget {
  _FakeWidget_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDateTime_4 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Mediator].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediator extends _i1.Mock implements _i6.Mediator {
  MockMediator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Pipeline get pipeline =>
      (super.noSuchMethod(
            Invocation.getter(#pipeline),
            returnValue: _FakePipeline_0(this, Invocation.getter(#pipeline)),
          )
          as _i2.Pipeline);

  @override
  Map<Type, _i6.HandlerCreator<dynamic>> get handlers =>
      (super.noSuchMethod(
            Invocation.getter(#handlers),
            returnValue: <Type, _i6.HandlerCreator<dynamic>>{},
          )
          as Map<Type, _i6.HandlerCreator<dynamic>>);

  @override
  Map<Type, List<_i7.IEventHandler<_i8.IDomainEvent>>> get eventHandlers =>
      (super.noSuchMethod(
            Invocation.getter(#eventHandlers),
            returnValue: <Type, List<_i7.IEventHandler<_i8.IDomainEvent>>>{},
          )
          as Map<Type, List<_i7.IEventHandler<_i8.IDomainEvent>>>);

  @override
  Map<Type, List<_i6.FuncEventHandler<_i8.IDomainEvent>>>
  get eventFuncHandler =>
      (super.noSuchMethod(
            Invocation.getter(#eventFuncHandler),
            returnValue: <Type, List<_i6.FuncEventHandler<_i8.IDomainEvent>>>{},
          )
          as Map<Type, List<_i6.FuncEventHandler<_i8.IDomainEvent>>>);

  @override
  _i6.UnsubscribeFunc subscribeWithFunc<E extends _i8.IDomainEvent>(
    _i3.FutureOr<void> Function(_i8.IDomainEvent)? func,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeWithFunc, [func]),
            returnValue: () {},
          )
          as _i6.UnsubscribeFunc);

  @override
  void subscribe<E extends _i8.IDomainEvent>(_i7.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#subscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribe<E extends _i8.IDomainEvent>(_i7.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#unsubscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> publish<E extends _i8.IDomainEvent>(E? event) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<R> send<T extends _i9.IRequest<R>, R extends Object?>(
    T? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#send, [request]),
                  ),
                  (R v) => _i3.Future<R>.value(v),
                ) ??
                _FakeFuture_1<R>(this, Invocation.method(#send, [request])),
          )
          as _i3.Future<R>);

  @override
  void registerHandler<
    IR extends _i9.IRequest<R>,
    R,
    H extends _i11.IRequestHandler<IR, R>
  >(_i6.HandlerCreator<H>? creator) => super.noSuchMethod(
    Invocation.method(#registerHandler, [creator]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TasksService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksService extends _i1.Mock implements _i12.TasksService {
  MockTasksService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ValueNotifier<String?> get onTaskCreated =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskCreated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskCreated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTaskUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskUpdated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskUpdated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTaskDeleted =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskDeleted),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskDeleted),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTaskTimeRecordUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskTimeRecordUpdated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskTimeRecordUpdated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTaskCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#onTaskCompleted),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTaskCompleted),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void notifyTaskCreated(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskCreated, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTaskUpdated(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskUpdated, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTaskDeleted(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskDeleted, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTaskTimeRecordUpdated(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskTimeRecordUpdated, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTaskCompleted(String? taskId) => super.noSuchMethod(
    Invocation.method(#notifyTaskCompleted, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ITranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITranslationService extends _i1.Mock
    implements _i14.ITranslationService {
  MockITranslationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String translate(String? key, {Map<String, String>? namedArgs}) =>
      (super.noSuchMethod(
            Invocation.method(#translate, [key], {#namedArgs: namedArgs}),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#translate, [key], {#namedArgs: namedArgs}),
            ),
          )
          as String);

  @override
  _i3.Future<void> changeLanguage(
    _i5.BuildContext? context,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [context, languageCode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> changeLanguageWithoutNavigation(
    _i5.BuildContext? context,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguageWithoutNavigation, [
              context,
              languageCode,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String getCurrentLanguage(_i5.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLanguage, [context]),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#getCurrentLanguage, [context]),
            ),
          )
          as String);

  @override
  _i5.Widget wrapWithTranslations(_i5.Widget? child) =>
      (super.noSuchMethod(
            Invocation.method(#wrapWithTranslations, [child]),
            returnValue: _FakeWidget_3(
              this,
              Invocation.method(#wrapWithTranslations, [child]),
            ),
          )
          as _i5.Widget);
}

/// A class which mocks [ITaskRecurrenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRecurrenceService extends _i1.Mock
    implements _i15.ITaskRecurrenceService {
  MockITaskRecurrenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isRecurring(_i16.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#isRecurring, [task]),
            returnValue: false,
          )
          as bool);

  @override
  bool canCreateNextInstance(_i16.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#canCreateNextInstance, [task]),
            returnValue: false,
          )
          as bool);

  @override
  DateTime calculateNextRecurrenceDate(
    _i16.Task? task,
    DateTime? currentDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateNextRecurrenceDate, [
              task,
              currentDate,
            ]),
            returnValue: _FakeDateTime_4(
              this,
              Invocation.method(#calculateNextRecurrenceDate, [
                task,
                currentDate,
              ]),
            ),
          )
          as DateTime);

  @override
  List<_i17.WeekDays>? getRecurrenceDays(_i16.Task? task) =>
      (super.noSuchMethod(Invocation.method(#getRecurrenceDays, [task]))
          as List<_i17.WeekDays>?);

  @override
  _i3.Future<String?> handleCompletedRecurringTask(
    String? taskId,
    _i6.Mediator? mediator,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleCompletedRecurringTask, [
              taskId,
              mediator,
            ]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [TagsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagsService extends _i1.Mock implements _i18.TagsService {
  MockTagsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ValueNotifier<String?> get onTagCreated =>
      (super.noSuchMethod(
            Invocation.getter(#onTagCreated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTagCreated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTagUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onTagUpdated),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTagUpdated),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  _i4.ValueNotifier<String?> get onTagDeleted =>
      (super.noSuchMethod(
            Invocation.getter(#onTagDeleted),
            returnValue: _FakeValueNotifier_2<String?>(
              this,
              Invocation.getter(#onTagDeleted),
            ),
          )
          as _i4.ValueNotifier<String?>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void notifyTagCreated(String? tagId) => super.noSuchMethod(
    Invocation.method(#notifyTagCreated, [tagId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTagUpdated(String? tagId) => super.noSuchMethod(
    Invocation.method(#notifyTagUpdated, [tagId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTagDeleted(String? tagId) => super.noSuchMethod(
    Invocation.method(#notifyTagDeleted, [tagId]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
