// Mocks generated by Mockito 5.4.5 from annotations
// in whph/test/presentation/ui/features/about/services/changelog_dialog_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/widgets.dart' as _i4;
import 'package:mediatr/mediatr.dart' as _i5;
import 'package:mediatr/src/internals/i_domain_event.dart' as _i7;
import 'package:mediatr/src/internals/i_event_handler.dart' as _i6;
import 'package:mediatr/src/internals/i_request.dart' as _i8;
import 'package:mediatr/src/internals/i_request_handler.dart' as _i10;
import 'package:mediatr/src/internals/pipeline.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:application/features/settings/queries/get_setting_query.dart'
    as _i13;
import 'package:domain/features/settings/setting.dart' as _i14;
import 'package:whph/presentation/ui/features/about/services/abstraction/i_changelog_service.dart'
    as _i11;
import 'package:whph/presentation/ui/shared/services/abstraction/i_translation_service.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePipeline_0 extends _i1.SmartFake implements _i2.Pipeline {
  _FakePipeline_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_2 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Mediator].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediator extends _i1.Mock implements _i5.Mediator {
  MockMediator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Pipeline get pipeline =>
      (super.noSuchMethod(
            Invocation.getter(#pipeline),
            returnValue: _FakePipeline_0(this, Invocation.getter(#pipeline)),
          )
          as _i2.Pipeline);

  @override
  Map<Type, _i5.HandlerCreator<dynamic>> get handlers =>
      (super.noSuchMethod(
            Invocation.getter(#handlers),
            returnValue: <Type, _i5.HandlerCreator<dynamic>>{},
          )
          as Map<Type, _i5.HandlerCreator<dynamic>>);

  @override
  Map<Type, List<_i6.IEventHandler<_i7.IDomainEvent>>> get eventHandlers =>
      (super.noSuchMethod(
            Invocation.getter(#eventHandlers),
            returnValue: <Type, List<_i6.IEventHandler<_i7.IDomainEvent>>>{},
          )
          as Map<Type, List<_i6.IEventHandler<_i7.IDomainEvent>>>);

  @override
  Map<Type, List<_i5.FuncEventHandler<_i7.IDomainEvent>>>
  get eventFuncHandler =>
      (super.noSuchMethod(
            Invocation.getter(#eventFuncHandler),
            returnValue: <Type, List<_i5.FuncEventHandler<_i7.IDomainEvent>>>{},
          )
          as Map<Type, List<_i5.FuncEventHandler<_i7.IDomainEvent>>>);

  @override
  _i5.UnsubscribeFunc subscribeWithFunc<E extends _i7.IDomainEvent>(
    _i3.FutureOr<void> Function(_i7.IDomainEvent)? func,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeWithFunc, [func]),
            returnValue: () {},
          )
          as _i5.UnsubscribeFunc);

  @override
  void subscribe<E extends _i7.IDomainEvent>(_i6.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#subscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribe<E extends _i7.IDomainEvent>(_i6.IEventHandler<E>? handler) =>
      super.noSuchMethod(
        Invocation.method(#unsubscribe, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> publish<E extends _i7.IDomainEvent>(E? event) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<R> send<T extends _i8.IRequest<R>, R extends Object?>(
    T? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#send, [request]),
                  ),
                  (R v) => _i3.Future<R>.value(v),
                ) ??
                _FakeFuture_1<R>(this, Invocation.method(#send, [request])),
          )
          as _i3.Future<R>);

  @override
  void registerHandler<
    IR extends _i8.IRequest<R>,
    R,
    H extends _i10.IRequestHandler<IR, R>
  >(_i5.HandlerCreator<H>? creator) => super.noSuchMethod(
    Invocation.method(#registerHandler, [creator]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IChangelogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChangelogService extends _i1.Mock implements _i11.IChangelogService {
  MockIChangelogService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i11.ChangelogEntry?> fetchChangelog(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchChangelog, [localeCode]),
            returnValue: _i3.Future<_i11.ChangelogEntry?>.value(),
          )
          as _i3.Future<_i11.ChangelogEntry?>);
}

/// A class which mocks [ITranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITranslationService extends _i1.Mock
    implements _i12.ITranslationService {
  MockITranslationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String translate(String? key, {Map<String, String>? namedArgs}) =>
      (super.noSuchMethod(
            Invocation.method(#translate, [key], {#namedArgs: namedArgs}),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#translate, [key], {#namedArgs: namedArgs}),
            ),
          )
          as String);

  @override
  _i3.Future<void> changeLanguage(
    _i4.BuildContext? context,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [context, languageCode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> changeLanguageWithoutNavigation(
    _i4.BuildContext? context,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguageWithoutNavigation, [
              context,
              languageCode,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String getCurrentLanguage(_i4.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLanguage, [context]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getCurrentLanguage, [context]),
            ),
          )
          as String);

  @override
  _i4.Widget wrapWithTranslations(_i4.Widget? child) =>
      (super.noSuchMethod(
            Invocation.method(#wrapWithTranslations, [child]),
            returnValue: _FakeWidget_2(
              this,
              Invocation.method(#wrapWithTranslations, [child]),
            ),
          )
          as _i4.Widget);
}

/// A class which mocks [GetSettingQueryResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSettingQueryResponse extends _i1.Mock
    implements _i13.GetSettingQueryResponse {
  MockGetSettingQueryResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get key =>
      (super.noSuchMethod(
            Invocation.getter(#key),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#key)),
          )
          as String);

  @override
  set key(String? _key) => super.noSuchMethod(
    Invocation.setter(#key, _key),
    returnValueForMissingStub: null,
  );

  @override
  String get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#value),
            ),
          )
          as String);

  @override
  set value(String? _value) => super.noSuchMethod(
    Invocation.setter(#value, _value),
    returnValueForMissingStub: null,
  );

  @override
  _i14.SettingValueType get valueType =>
      (super.noSuchMethod(
            Invocation.getter(#valueType),
            returnValue: _i14.SettingValueType.string,
          )
          as _i14.SettingValueType);

  @override
  set valueType(_i14.SettingValueType? _valueType) => super.noSuchMethod(
    Invocation.setter(#valueType, _valueType),
    returnValueForMissingStub: null,
  );

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  set id(String? _id) => super.noSuchMethod(
    Invocation.setter(#id, _id),
    returnValueForMissingStub: null,
  );

  @override
  DateTime get createdDate =>
      (super.noSuchMethod(
            Invocation.getter(#createdDate),
            returnValue: _FakeDateTime_3(this, Invocation.getter(#createdDate)),
          )
          as DateTime);

  @override
  set createdDate(DateTime? _createdDate) => super.noSuchMethod(
    Invocation.setter(#createdDate, _createdDate),
    returnValueForMissingStub: null,
  );

  @override
  set modifiedDate(DateTime? _modifiedDate) => super.noSuchMethod(
    Invocation.setter(#modifiedDate, _modifiedDate),
    returnValueForMissingStub: null,
  );

  @override
  set deletedDate(DateTime? _deletedDate) => super.noSuchMethod(
    Invocation.setter(#deletedDate, _deletedDate),
    returnValueForMissingStub: null,
  );

  @override
  bool get isDeleted =>
      (super.noSuchMethod(Invocation.getter(#isDeleted), returnValue: false)
          as bool);

  @override
  T getValue<T>() =>
      (super.noSuchMethod(
            Invocation.method(#getValue, []),
            returnValue: _i9.dummyValue<T>(
              this,
              Invocation.method(#getValue, []),
            ),
          )
          as T);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
