name: Flutter CI - Android

on:
  workflow_dispatch: # This is a trigger for manual workflow run
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Initialize Submodules
        uses: ./.github/actions/setup-repository

      - name: Setup Flutter with FVM
        uses: ./.github/actions/setup-fvm
        with:
          cache-key-suffix: "android"

      - name: Install Flutter Dependencies
        uses: ./.github/actions/install-flutter-deps

      - name: Install OpenJDK 17 from apt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-17-jdk-headless

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Remove non-Android platforms
        run: |
          cd src
          rm -rf ios linux macos web windows

      - name: Setup Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > src/android/app/whph-release.keystore

      - name: Update Gradle Properties
        run: |
          cat << EOF > src/android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=whph-release.keystore
          EOF

      - name: Build for Android
        run: |
          cd src
          fvm flutter build apk --release

      # Publish the build artifacts
      - name: Get application version
        id: app_version
        uses: ./.github/actions/get-app-version

      - name: Upload Android build artifact
        uses: ./.github/actions/upload-build-artifact
        with:
          artifact-name: android
          artifact-path: src/build/app/outputs/flutter-apk/app-release.apk
          app-version: ${{ steps.app_version.outputs.version }}
          compression-level: "0"
