name: Flutter CI - Android

on:
  workflow_dispatch: # This is a trigger for manual workflow run
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    # Build for Android
    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Fix Android Packages
      run: flutter pub run rps fix-android

    - name: Build for Android
      run: flutter build apk --release
    
    # Publish the build artifacts
    - name: Get application version
      id: app_version
      run: |
        APP_VERSION=$(awk '/^version:/ {print $2}' pubspec.yaml)
        echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

    - name: Upload Android build artifact
      uses: actions/upload-artifact@v4
      with:
        name: whph-v${{ env.APP_VERSION }}-android
        path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get application version
        id: app_version
        run: |
          APP_VERSION=$(awk '/^version:/ {print $2}' pubspec.yaml)
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: whph-v${{ env.APP_VERSION }}-android
          path: android-build

      - name: Check existing release
        id: check_release
        run: |
          RELEASE_TAG="${{ github.ref_name }}"
          if gh release view "$RELEASE_TAG" &>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag name
        id: tag_name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Get tag version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Rename APK
        run: |
          mv android-build/app-release.apk android-build/whph-v${TAG_VERSION}-android.apk

      # Create or update the release
      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: android-build/whph-v${{ env.TAG_VERSION }}-android.apk
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: ${{ steps.check_release.outputs.exists == 'false' }}
          append_body: ${{ steps.check_release.outputs.exists == 'true' }}
          replace_artifacts: false
